### PR TITLE
fix(sns): enforce FilterPolicy on message delivery

### LINKED ISSUE #49: [BUG] SNS Message Filter Policy Enforcement
## Service

SNS

## API Action / Feature

Enforce `FilterPolicy` subscription attribute during `Publish` and `PublishBatch` operations.

## AWS Documentation

- https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html
- https://docs.aws.amazon.com/sns/latest/dg/sns-subscription-filter-policies.html

## Why is this needed?

Message filtering is one of the most commonly used SNS features. Applications use filter policies to route messages from a single topic to different SQS queues based on message attributes — for example, sending "order" events to an order-processing queue and "payment" events to a payment queue.

Currently, floci accepts the `FilterPolicy` subscription attribute via `SetSubscriptionAttributes` and returns it via `GetSubscriptionAttributes`, but **never evaluates it during message delivery**. All messages are delivered to all confirmed subscriptions regardless of their filter policies.

This means any application relying on SNS filtering for message routing will receive every message on every subscriber, which:
1. Breaks message routing logic entirely
2. Causes downstream consumers to process irrelevant messages
3. Makes it impossible to test filtering-dependent architectures locally

LocalStack implements full filter policy evaluation including:
- Exact string matching
- Prefix/suffix matching
- Numeric comparisons (=, <, >, <=, >=)
- `anything-but` operators
- `exists` operators
- `$or` operators
- Both `MessageAttributes` and `MessageBody` scopes (`FilterPolicyScope`)

## Expected behavior

```bash
# Create topic
TOPIC_ARN=$(aws sns create-topic --name my-topic --endpoint-url http://localhost:4566 --query TopicArn --output text)

# Create two SQS queues
aws sqs create-queue --queue-name orders --endpoint-url http://localhost:4566
aws sqs create-queue --queue-name payments --endpoint-url http://localhost:4566

# Subscribe both queues
ORDER_SUB=$(aws sns subscribe --topic-arn $TOPIC_ARN --protocol sqs \
  --notification-endpoint arn:aws:sqs:us-east-1:000000000000:orders \
  --endpoint-url http://localhost:4566 --query SubscriptionArn --output text)

PAYMENT_SUB=$(aws sns subscribe --topic-arn $TOPIC_ARN --protocol sqs \
  --notification-endpoint arn:aws:sqs:us-east-1:000000000000:payments \
  --endpoint-url http://localhost:4566 --query SubscriptionArn --output text)

# Set filter policies
aws sns set-subscription-attributes --subscription-arn $ORDER_SUB \
  --attribute-name FilterPolicy \
  --attribute-value '{"event_type": ["order"]}' \
  --endpoint-url http://localhost:4566

aws sns set-subscription-attributes --subscription-arn $PAYMENT_SUB \
  --attribute-name FilterPolicy \
  --attribute-value '{"event_type": ["payment"]}' \
  --endpoint-url http://localhost:4566

# Publish an order event
aws sns publish --topic-arn $TOPIC_ARN \
  --message "Order created" \
  --message-attributes '{"event_type":{"DataType":"String","StringValue":"order"}}' \
  --endpoint-url http://localhost:4566

# Expected: only the "orders" queue receives the message
# Actual: BOTH queues receive the message (filter not enforced)
```

## Actual behavior

All messages are delivered to all confirmed subscriptions regardless of their `FilterPolicy` attribute. The filter policy is stored but never evaluated.

## Are you willing to contribute a PR?

Yes

### PR DESCRIPTION
**Pull request by rpalcolea**
FilterPolicy subscription attribute was accepted and stored but never evaluated during publish. Messages were delivered to all confirmed subscriptions regardless of filter rules. Now evaluates filter policies supporting exact string matching, numeric comparisons, prefix matching, exists operator, and anything-but operator per SNS specification.

Fixes #49

## Type of change

- [x] Bug fix (`fix:`)
- [ ] New feature (`feat:`)
- [ ] Breaking change (`feat!:` or `fix!:`)
- [ ] Docs / chore

## Checklist

- [x] `./mvnw test` passes locally
- [x] New or updated integration test added
- [x] Commit messages follow [Conventional Commits](https://www.conventionalcommits.org/)

### CODE REVIEW

File: src/main/java/io/github/hectorvent/floci/services/sns/SnsService.java [hunk 1]
```diff
@@ -386,6 +391,138 @@ public Map<String, String> listTagsForResource(String resourceArn, String region
...
+    }
+
+    private boolean containsValue(JsonNode node, String value) {
+        if (node.isArray()) {
+            for (JsonNode element : node) {
+                if (element.asText().equals(value)) return true;
+            }
+            return false;
+        }
+        return node.asText().equals(value);
```
Comment (hectorvent) [inline src/main/java/io/github/hectorvent/floci/services/sns/SnsService.java]:
```suggestion
        }
        // Per SNS spec, anything-but must be an array. Log and fall back to scalar comparison
        // so we don't silently drop messages on misconfigured policies.
        LOG.warnv("SNS FilterPolicy: 'anything-but' value should be an array but got: {0}. Treating as single-value list.", node.getNodeType());
        return node.asText().equals(value);
```

File: src/main/java/io/github/hectorvent/floci/services/sns/SnsService.java [hunk 2]
```diff
@@ -386,6 +391,138 @@ public Map<String, String> listTagsForResource(String resourceArn, String region
...
+        }
+        for (JsonNode rule : rules) {
+            if (rule.isTextual() && rule.asText().equals(actualValue)) {
+                return true;
+            }
+            if (rule.isNumber() && actualValue != null) {
+                try {
+                    if (Double.parseDouble(actualValue) == rule.asDouble()) {
+                        return true;
+                    }
```
Comment (hectorvent) [inline src/main/java/io/github/hectorvent/floci/services/sns/SnsService.java]: With `BigDecimal` we preserve the exact value written in the filter policy (e.g. "100.10" stays 100.10, not 100.09999...)

```suggestion
                    // preserves exact representation
                    BigDecimal expected = new BigDecimal(rule.asText()); 
                    if (actual.compareTo(expected) == 0) {
                        return true;
                    }
```

File: src/main/java/io/github/hectorvent/floci/services/sns/SnsService.java [hunk 3]
```diff
@@ -386,6 +391,138 @@ public Map<String, String> listTagsForResource(String resourceArn, String region
...
+        for (int i = 0; i < conditions.size(); i += 2) {
+            String op = conditions.get(i).asText();
+            double target = conditions.get(i + 1).asDouble();
+            boolean matches = switch (op) {
+                case "=" -> value == target;
+                case ">" -> value > target;
+                case ">=" -> value >= target;
+                case "<" -> value < target;
+                case "<=" -> value <= target;
+                default -> false;
```
Comment (hectorvent) [inline src/main/java/io/github/hectorvent/floci/services/sns/SnsService.java]:
```suggestion
            BigDecimal target = new BigDecimal(conditions.get(i + 1).asText());
            int cmp = value.compareTo(target);
            boolean matches = switch (op) {
                case "="  -> cmp == 0;
                case ">"  -> cmp >  0;
                case ">=" -> cmp >= 0;
                case "<"  -> cmp <  0;
                case "<=" -> cmp <= 0;
                default -> false;
```

**Comment by hectorvent** [comment]
Thanks again, @rpalcolea!

merging
