### PR TITLE
fix(dynamodb): respect `if_not_exists` for `update_item`

### LINKED ISSUE #94: [BUG] DynamoDB UpdateItem with if_not_exists does not persist attributes when creating a new item
## Service

DynamoDB

## AWS API Action

UpdateItem

## Expected behavior

When `UpdateItem` is called on a non-existent item with `SET attr = if_not_exists(attr, :val)`, the item should be created with both the key attributes and the SET attributes (matching real AWS behavior).

## Actual behavior

The item is created with key attributes only. The attributes specified in the `SET ... if_not_exists(...)` expression are silently dropped.

Note: `if_not_exists` works correctly when the item already exists (correctly preserves the existing value).

## Reproduction

```python
import boto3

db = boto3.client('dynamodb', endpoint_url='http://localhost:4566',
                  region_name='ap-northeast-1',
                  aws_access_key_id='test', aws_secret_access_key='test')

db.create_table(
    TableName='TestTable',
    KeySchema=[
        {'AttributeName': 'pk', 'KeyType': 'HASH'},
        {'AttributeName': 'sk', 'KeyType': 'RANGE'}
    ],
    AttributeDefinitions=[
        {'AttributeName': 'pk', 'AttributeType': 'S'},
        {'AttributeName': 'sk', 'AttributeType': 'S'}
    ],
    BillingMode='PAY_PER_REQUEST'
)

# UpdateItem on non-existent item with if_not_exists
db.update_item(
    TableName='TestTable',
    Key={'pk': {'S': '1'}, 'sk': {'S': 'sort1'}},
    UpdateExpression='SET price = if_not_exists(price, :val)',
    ExpressionAttributeValues={':val': {'N': '100'}}
)

resp = db.get_item(TableName='TestTable', Key={'pk': {'S': '1'}, 'sk': {'S': 'sort1'}})
print(resp['Item'])
# Actual:   {'pk': {'S': '1'}, 'sk': {'S': 'sort1'}}
# Expected: {'pk': {'S': '1'}, 'sk': {'S': 'sort1'}, 'price': {'N': '100'}}
```

## Environment

- Floci version / image tag: `hectorvent/floci:latest` (1.0.11)
- How you're running Floci: Docker

### PR DESCRIPTION
**Pull request by bruderj15**
Closes #94

## Summary

In `applySetClause` inside `DynamoDbService.java`, the value-resolution block only handled the simple `:placeholder` case:

```java
// Resolve the value
if (valuePart.startsWith(":") && exprAttrValues != null) {
    JsonNode value = exprAttrValues.get(valuePart);
    if (value != null) {
        item.set(attrName, value);
    }
}
```

When the `valuePart` was `if_not_exists(price, :val)`, the condition was false and the entire assignment was silently skipped 
— so `price` was never written to the item.

Therefore I added an `if_not_exists(...)` branch before the existing `:placeholder` branch in `applySetClause`.

## Type of change

- [x] Bug fix (`fix:`)
- [ ] New feature (`feat:`)
- [ ] Breaking change (`feat!:` or `fix!:`)
- [ ] Docs / chore

## Checklist

- [x] `./mvnw test` passes locally
- [x] New or updated integration test added
- [x] Commit messages follow [Conventional Commits](https://www.conventionalcommits.org/)

### CODE REVIEW

File: src/main/java/io/github/hectorvent/floci/services/dynamodb/DynamoDbService.java [hunk 1]
```diff
@@ -887,11 +888,42 @@ private String applySetClause(ObjectNode item, String clause,
             }
 
             // Resolve the value
-            if (valuePart.startsWith(":") && exprAttrValues != null) {
+            String valueLower = valuePart.toLowerCase(Locale.ROOT);
+            if (valueLower.startsWith("if_not_exists(")) {
```
Comment (hectorvent) [inline src/main/java/io/github/hectorvent/floci/services/dynamodb/DynamoDbService.java]: This is too permissive 

```suggestion
            if (valuePart.startsWith("if_not_exists(")) {
```

**Review by hectorvent — APPROVED** [review]
